### ISSUE TITLE
[Feature Request] Dark theme

### ISSUE THREAD

**Issue by amuro0079** [ProtonMail/proton-mail-android#69] opened 2021-02-11 08:32 UTC
Most of email clients have a dark theme, ProtonMail should have one too.

**Comment by xster** [comment] 2021-02-18 06:06
Seems like a dupe of https://github.com/ProtonMail/proton-mail-android/issues/32

**Comment by marinomeneghel** [comment] 2021-02-24 22:16
Agreed, closing as the feature request is being tracked by #32.

@amuro0079 please feel free to add any additional comments there

**Closed** 2021-02-24 22:16 UTC
Labels: enhancement
