### ISSUE TITLE
[Bug] WKD address is not recognized

### ISSUE THREAD

**Issue by micressor** [ProtonMail/proton-mail-android#44] opened 2020-10-14 09:10 UTC
**Describe the bug**
When creating a new e-mail it is not recognized that the (non protonmail) target e-mail address publishes a WKD key.

**To Reproduce**
1. Go to 'ProtonMail' on Android
2. Click on 'Pencil (to send a new message)'
3. Click on 'To' field and type a 'wkd capable e-mail address'
4. See error: 'ProtonMail will only sign the email (not encrypt)'

**Expected behavior**
The app should recognize the [WKD capable address](https://metacode.biz/openpgp/web-key-directory
) and encrypt the email accordingly.

**Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - OS: LineageOS 16.0-20191011 (Android 9)

**Related links found:**
https://github.com/ProtonMail/proton-contacts/issues/134

**Comment by micressor** [comment] 2020-10-14 14:50
@bartbutler Yes verified. Via web app (mail.protonmail.com) it works proper.

**Comment by SuperdukeGates** [comment] 2020-11-05 10:48
I also encountered this bug today for addresses from certain domain. My phone is Android 10, the ProtonMail app is a beta version 1.13.18 (741). At the mean time, the web ProtonMail is fine.

My experience is that I have a domain like this for example aa.bb.cc, the address abcd@**aa.bb.cc** is a WKD capable address and it is fine.

When I use the WKD capable address abcd@**ddd.cc** for example, then the bug was happened.

**Comment by worldofgeese** [comment] 2021-09-02 20:33
Can you please take a look at this, @bartbutler? It's more than a year now without feature parity with the web app.

**Comment by zcyph** [comment] 2022-12-27 06:21
This is still not working. This feature was launched over [3 years ago](https://proton.me/blog/security-updates-2019).

Can someone please take a look? Are more examples / troubleshooting required? Please respond.

**Comment by xpseudonym** [comment] 2023-04-28 15:54
I just tell all my clients to get a ProtonMail account - but, not to use the apps because they're insecure, unsafe and broken - not a good look if you ask me Proton...

**Comment by xpseudonym** [comment] 2023-04-28 15:59
btw, is it also broken in the iOS app?

**Comment by bartbutler** [comment] 2023-05-01 13:57
While I have not verified this myself yet, I was told by the devs that this should be fixed in version 3.0.12 and above.

**Closed by bartbutler** 2023-05-01 13:57 UTC
Labels: bug

**Comment by xpseudonym** [comment] 2023-05-01 14:15
Yup, I can confirm that.  Thanks @bartbutler
