### ISSUE TITLE
Bug with adding attachments

### ISSUE THREAD

**Issue by ayc9** [ProtonMail/proton-mail-android#39] opened 2020-08-24 22:53 UTC
### Expected behavior
Successful sending of an attachment in an email. 

### Current behavior
Attachment cannot be added to an email. Returning to the message composition page loses body and subject of the email if previously entered. 

### Steps to reproduce 

1. Open app and log in.
2. Click compose message icon on top right.
3. Start composing the email (select address to send from and to send to, fill in subject, write in body). See image 1 below.
4. Select attachment icon (see image 2) and then select an attachment (either using the camera or files on the device storage).
5. You see two sections on the screen (see the 3rd image below). Go back to email composition screen using top left button or back button on phone. 
(5.5. After choosing an attachment and finding yourself on a screen like in the 3rd image below, you can select the chosen attachment to preview it. Returning to the attachments list shows an empty list again like in image 2.)
6. You return to an empty message body, and a subject replaced with "(No Subject)". The email addresses are kept intact. The attachment is lost. See image 4.

### My Environment
Android version: 8.0.0
Device model: SM-G960U
App version: 1.13.10 (729)

![20200824_183515](https://user-images.githubusercontent.com/48227009/91103118-b6f09a80-e638-11ea-8896-c94bf3124117.jpg)
Image 1: drafting a new email. 
![Screenshot_20200824-182721_ProtonMail](https://user-images.githubusercontent.com/48227009/91102829-fbc80180-e637-11ea-9918-5e088ef6e7e4.jpg)
Image 2: screen after selecting attachment icon. 
![Screenshot_20200824-182847_ProtonMail](https://user-images.githubusercontent.com/48227009/91102831-fe2a5b80-e637-11ea-95e5-4365f0ce18db.jpg)
Image 3: screen after selecting a file to attach. 
![20200824_183454](https://user-images.githubusercontent.com/48227009/91103128-c07a0280-e638-11ea-9335-d2af4916e1e2.jpg)

Image 4: returning to draft shows lost progress.

**Comment by anantdark** [comment] 2020-08-27 11:04
I experienced the same bug today. While composing the email, the attachment was there.
But when I opened it in the `sent` folder, the email was sent without attachment.

Then I sent the mail through the website, it worked fine. It seems there is a critical bug in the app.
In this image, I had sent email 1 from the app, but when it was sent without attachment, I had to send the email 2 again from the website.

I had encrypted the mail with a password as I was sending it to a non-protonmail account.

![droid_11](https://user-images.githubusercontent.com/66427020/91434380-3f975280-e854-11ea-9159-39a0bac82b03.jpg)

**Comment by kwojwaj** [comment] 2020-08-31 11:16
Thank you for your reports. We will look into it. Please contact our customer support team directly at support@protonmail.com if you would like further updates on the issue.

**Comment by 4face-studi0** [comment] 2020-08-31 20:01
I'd add also "to ensure to have an higher priority" :)

**Comment by anantdark** [comment] 2020-10-04 22:36
The bug is still open. I thought it would have been fixed by now, as it is of "higher priority". :-1:

**Comment by marinomeneghel** [comment] 2020-12-01 19:41
@anantdark a fix for the bug you raised is being worked on internally, we'll come back with updates on when it will be released as soon as it's finalised.
Regarding the one initially reported by @ayc9 I guess a fix was rolled out already as I can't reproduce it in the latest production version. 
Thanks for your patience!

**Comment by prov3it** [comment] 2021-01-22 20:32
I have the exact same issue on a freshly installed android tablet. 

Device: Lenovo TB-8705F
App version: 1.13.24 (751)
Android version: 10

**Comment by ayc9** [comment] 2021-01-28 21:05
I just reproduced it, app version is 1.13.25 (754)

**Comment by CorruptComputer** [comment] 2021-02-02 21:33
I would also like to add to this, that if you attach something to an email then save it as a draft, when you try to open that draft on the Web client the attachments will not be there. So anytime I want to start an email on my phone, then wait to send it until I'm at my PC I need to transfer whatever attachment I was trying to add to the email to my PC and re-attach it before sending the email.

This is especially frustrating when trying to reply to an HTML formatted email with a screenshot attached but having issues writing the actual email on my phone because of the apps slimmed down editor. This is an issue I run into on almost a daily basis.

**Comment by marinomeneghel** [comment] 2021-04-07 07:46
@ayc9 @anantdark @CorruptComputer with the latest beta (764) we're rolling out a set of improvements regarding attachments that are resolving the three issues that were raised in here. 

We're happy to hear any feedback if you try it out!

**Comment by CorruptComputer** [comment] 2021-04-11 15:10
I just got the chance to test this again, and the issue that I was seeing with the attachments not transferring between phone and web doesn't seem to be happening anymore. Thanks for the fix!

**Comment by anantdark** [comment] 2021-04-27 22:06
Yep, I tried to reproducing the bug, I think it is fixed in the new update. Thanks team!!

**Comment by marinomeneghel** [comment] 2021-04-28 07:22
Thanks both for the feedback, that's great! 

I'll go on and close this, please feel free to re-open / create a new issue in case any additional discussion on the topic is needed.

**Closed by marinomeneghel** 2021-04-28 07:22 UTC
Labels: bug
