### ISSUE TITLE
[Feature Request] Remove unnecessary READ_EXTERNAL_STORAGE permission when adding an attachment

### ISSUE THREAD

**Issue by besamim** [ProtonMail/proton-mail-android#88] opened 2021-04-27 15:50 UTC
Remove unnecessary READ_EXTERNAL_STORAGE permission when adding an attachment. It is not privacy-friendly and absolutely not needed to ask for the media files permission when using the Storage Access Framework to let the user choose files. It's also not at all needed for launching the camera! Please fix this ASAP.

**Comment by marinomeneghel** [comment] 2021-05-13 07:35
Hi @besamim , I noticed this issue is a duplicate of #91 which you also created. Since #91 has some more details will close this one and followup there

**Closed by marinomeneghel** 2021-05-13 07:35 UTC
Labels: enhancement
