### ISSUE TITLE
[Feature Request] Group mails

### ISSUE THREAD

**Issue by Norbiros** [ProtonMail/proton-mail-android#174] opened 2022-07-05 19:47 UTC
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when im reading Github mail notifications, because mails don't group to one chain like in web client (for example if you are replying it shows one message with mail and responses).

Ignore those lines and numbers, I am talking about groups:
![96462831-90547780-1215-11eb-9ba7-830498d620d4](https://user-images.githubusercontent.com/89837724/177405477-3a442a01-e807-4a2c-9859-bfb9cade8c6b.jpg)

**Describe the solution you'd like**
Group mails with the same title to one chain like in web client.

**Additional context**
None

**Comment by keithfancher** [comment] 2022-12-27 18:09
I think this one's a dupe of https://github.com/ProtonMail/proton-mail-android/issues/12. We may as well all pile on to that one issue and keep asking for this feature :smile:

**Comment by Norbiros** [comment] 2022-12-27 21:30
Closed as dupe of #12

**Closed** 2022-12-27 21:30 UTC
Labels: enhancement
