### ISSUE TITLE
[Bug] Unread count in app different to web interface + message discrepancies

### ISSUE THREAD

**Issue by nbgh1** [ProtonMail/proton-mail-android#55] opened 2020-11-26 01:37 UTC
Hi,

I have noticed some issues in the ProtonMail Android app:

### System Details

* Android 11
* ProtonMail App version 1.13.22 (beta channel)

### The issues

I have noticed two problems:

1. The number of unread messages reported by the app is incorrect, the web interface (version 3.16.46) is reporting the correct number.

* The app shows 4 additional unread messages that do not exist
* I have further tested by emailing myself, the count does increment by one in both the app and web interface, but the count in the app is still off by 4

Clearing the app cache does not remedy this problem. I have not cleared app data yet, as this may destroy data needed for debugging.

I will add too, that this is not simply a propagation delay, this issue has persisted for several days.

##### Web interface (correct values)

![proton-web](https://user-images.githubusercontent.com/74638753/100297835-b70b8800-2fe3-11eb-8c67-84991f530e0b.png)

##### Android app (incorrect values)

![proton-android](https://user-images.githubusercontent.com/74638753/100297841-b8d54b80-2fe3-11eb-8412-e315ce7d96fe.png)

2. I noticed (for the first time) an email received (25/11/20 17:58 AEST) from another ProtonMail user was marked as read in my inbox, though I did not open it or mark it as read and did not receive a push notification for it. This has only occurred once and I can not replicate it (tested sending messages to myself from ProtonMail and Gmail).

I am confident this is not the result of someone else having access to my account or any other nefarious thing:

* My account has a strong, unique password and MFA configured for it 
* It is only accessed by myself from secured and fully patched devices using the web portal or official app from Google Play
* The security page of ProtonMail lists no unknown sessions or logins from unrecognised IP addresses

There is a slight possibility I may have tapped the notification inadvertently while switching between applications as I was using several apps on the phone at the time Proton records the message as being received. If this occurred, it could have resulted in the message being opened in the app while it was not in focus. I do not think this is what happened, but I raise it as a possibility.

### Reproduction

As explained, these issues are either omnipresent without a clear root cause (issue 1) or challenging to reproduce (issue 2).

### Analysis

I believe these issues could be related to the adoption of FCM in the latest release https://github.com/ProtonMail/proton-mail-android/releases/tag/1.13.21

A significant change in how push and notifications work in the app, followed by related bugs seems unlikely to be a coincidence to me...

I would welcome any commentary from the ProtonMail team or from any other user experiencing this or similar issues. I would be most happy to provide additional information or assist in further debugging.

**Comment by 4face-studi0** [comment] 2020-11-26 06:24
Thanks @nbgh1 for the report.

Isn't this a duplicate of #45

**Comment by bartbutler** [comment] 2020-11-27 00:39
@nbgh1 can you please contact customer support with your username/email via support AT protonmail.com and tell them to bring this to my attention? This is unlikely to be an Android bug and more likely to be a server-side inconsistency.

**Comment by nbgh1** [comment] 2020-11-29 14:12
> @nbgh1 can you please contact customer support with your username/email via support AT protonmail.com and tell them to bring this to my attention? This is unlikely to be an Android bug and more likely to be a server-side inconsistency.

Thank you, I shall.

**Comment by nbgh1** [comment] 2020-11-29 14:16
> Thanks @nbgh1 for the report.
> 
> Isn't this a duplicate of #45

Potentially, it provides a plausible explaination for the first part of my issue, apologies for not noticing #45 (it was closed).

I shall follow up with @bartbutler in any case.

**Comment by nbgh1** [comment] 2020-12-08 09:49
Sorry for the belated update, I would like to confirm that the counters in the Android App and web client are the same if I disable "Conversation Mode" as explained in https://github.com/ProtonMail/proton-mail-android/issues/45

```
Settings > Appereance > Conversation Grouping
```

It would seem I have simply misunderstood the feature parity between the Android and web clients.

In terms of my second issue (the "read" message), I am happy to follow up with @bartbutler via email support, I would be interested to know if the theory about the "server-side inconsistency" proved accurate?

I am happy for this issue to be closed as a duplicate, but will leave it to the discretion of the Proton team, since two discrete cases are described and only one is accounted for :)

Thank you!

**Comment by bartbutler** [comment] 2020-12-08 09:58
Glad to see the count discrepancy is resolved. In terms of the message marked as read, hard to debug if it can't be reproduced. I will close for now--feel free too reopen or open another ticket it it reappears.

**Closed by bartbutler** 2020-12-08 09:58 UTC
Labels: bug

**Comment by nbgh1** [comment] 2020-12-08 10:07
> Glad to see the count discrepancy is resolved. In terms of the message marked as read, hard to debug if it can't be reproduced. I will close for now--feel free too reopen or open another ticket it it reappears.

Thanks for that @bartbutler

Just in closing, what was the leading theory with the read message issue?

**Comment by bartbutler** [comment] 2020-12-08 10:21
The new message which was read? User misclick :)

**Comment by nbgh1** [comment] 2020-12-08 10:22
Fair enough, it is definitely possible :)
