### ISSUE TITLE
Problem with Thunderbird and cache

### ISSUE THREAD

**Issue by thekix** [ProtonMail/proton-mail-android#27] opened 2020-05-30 10:17 UTC
Hi,

when I am using the Android application and the web all is fine. With a new email, using the web, I can read, delete, move,... and the Android application is updated.

When I do the same using Thunderbird, web client is updated properly. I can delete an email in my inbox, and the mail is deleted in the web client. But the mail is not deleted in the android application. Other status, like read, moved,... are not updated in the Android application too. For example, I can read the email in Thunderbird, the mail is marked as read in the web client, but not in the Android application.

To solve the problem, I need to refresh local cache in the Android application and all is fine. But I cannot refresh the local cache every time.

The problem seems to be something like that there is no any push notification between the server and the mail application to update the mail status.

Regards,
kix

**Comment by jwflory** [comment] 2020-06-06 02:06
Oops. I only saw this issue title before I opened #28. But this is not a Thunderbird / ProtonMail Bridge issue. The ProtonMail Android client is not matching the same state as the IMAP server. To verify, if you log into ProtonMail on the web, you should see the same view as Thunderbird.

**Comment by 4face-studi0** [comment] 2020-08-11 18:12
Closing this as referenced in another issue, where the problem is less specific than what mentioned here

**Closed by 4face-studi0** 2020-08-11 18:12 UTC
Labels: bug
