### ISSUE TITLE
[Bug] APP CRUSHES!

### ISSUE THREAD

**Issue by ghost** [ProtonMail/proton-mail-android#209] opened 2023-02-18 08:33 UTC
Hello!
On my Samsung Galaxy S20 Ultra phone, the app won't start. It crashes as soon as the logo appears. Reinstalling it does not help.

More info:
Google services status: deleted by ADB method
Device model: SM-G988B/DS
Android version: 12 (updated to 13, issues persists)
App version: 3.0.11

GOOGLE SERVICES REMOVED COMPLETELY from my device (using ADB).

No root. No custom ROM.

**Comment by loyl1** [comment] 2023-04-22 15:34
How did you install it? Have you tried installing the GitHub version?

**Comment by DanielProg39** [comment] 2023-04-26 07:35
I have the same problem. I have other device, I haven't deleted Google services btw, I did not do any significant changes to my Android 12. I installed the app from IzzyOnDriod F-droid repo, so I basically use the GitHub version.
Here are some details:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.protonmail.android/ch.protonmail.android.mailbox.presentation.ui.MailboxActivity}: java.lang.SecurityException: Caller ch.protonmail.android needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3937)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.SecurityException: Caller ch.protonmail.android needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:375)
	at android.app.AlarmManager.setImpl(AlarmManager.java:947)
	at android.app.AlarmManager.setImpl(AlarmManager.java:907)
	at android.app.AlarmManager.setExact(AlarmManager.java:705)
	at ch.protonmail.android.api.segments.event.AlarmReceiver.setAlarm(AlarmReceiver.java:6)
	at ch.protonmail.android.mailbox.presentation.ui.MailboxActivity.t2(MailboxActivity.kt:54)
	at ch.protonmail.android.mailbox.presentation.ui.MailboxActivity.onCreate(MailboxActivity.kt:245)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
	... 12 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2546)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:201)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)
```
I have found some information regarding what it could be, hope this helps:

This error is occurring in an Android app and it is a security exception that is being thrown when the app is trying to set an exact alarm. The error message says that the caller, which is the `ch.protonmail.android` app, needs to hold the `android.permission.SCHEDULE_EXACT_ALARM` permission to set exact alarms.

This error is caused by the fact that starting with Android 10, the `SCHEDULE_EXACT_ALARM` permission is required for apps to set alarms that fire at exact times. This is a security measure that prevents apps from abusing alarms to run in the background and consume battery life.

To fix this error, the app needs to request the `SCHEDULE_EXACT_ALARM` permission in the Android manifest file and also request it at runtime from the user. The app can use the `requestPermissions` method to request the permission from the user.

It is also important to note that setting exact alarms is a feature that should be used sparingly and only when necessary, as it can have a significant impact on the device's battery life.

**Comment by DanielProg39** [comment] 2023-04-26 08:12
As stated in #205, enabling "Allow setting alarms and reminders" resolves the problem, but this setting is hidden in some ROMs and not technical users would never discover what caused the crash and how to resolve it. So the app should clearly request this permission, if it needs it so much (for what, btw?).

**Comment by marinomeneghel** [comment] 2023-05-04 11:06
The alarms are used to keep the app in sync with the remote, (when the preference to do so is enabled).

The app is requiring this permission as visible [in the manifest](https://github.com/ProtonMail/proton-mail-android/blob/release/app/src/main/AndroidManifest.xml#L41), but it doesn't seem to be verifying that the permission was not revoked afterwards. 

Closing as it can be solved as suggested above.

**Closed by marinomeneghel** 2023-05-04 11:06 UTC
Labels: bug
