### ISSUE TITLE
[Startup crash] The app won't launch after update to 1.3.19

### ISSUE THREAD

**Issue by Xashyar** [ProtonMail/proton-mail-android#51] opened 2020-11-09 19:07 UTC
**Describe the bug**
Startup crash / failure to launch, only the logo screen is shown for a few seconds and then the app is quickly closed.

**Smartphone (please complete the following information):**
 - Device: Huawei P8 Lite
 - OS: Android 6.0
 - Version 1.3.19

**Additional context**
Couldn't include logs, since the app won't launch.

**Comment by do1fmd** [comment] 2020-11-10 09:53
Same problem here. Also Android Marshmallow.

**Comment by marinomeneghel** [comment] 2020-11-10 19:46
Hi @Xashyar , @do1fmd 
thanks for reporting this issue. 

We're looking into it and will get back with more info soon!

In order for you to keep using ProtonMail's app while we provide a fix, consider temporarily leaving the beta program on Google Play to go back to the official production version.

**Comment by marinomeneghel** [comment] 2020-11-11 09:25
The cause of this crash was identified and a fix in underway. It will be released with the next beta build which is going to be published within the next couple of days.

Please note that this repo will reflect the fixes only once the code reach the release channel

**Comment by ZoricaStojchevska** [comment] 2020-11-17 09:02
Fixed with [b738e90](https://github.com/ProtonMail/proton-mail-android/commit/b738e902ba2bf1de3beb02625b28b988a5f5951d)

**Closed** 2020-11-17 09:02 UTC
Labels: Dev completed, bug
